dist: trusty
os:  linux

language: cpp

compiler:
  - gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "FGX+wb7Ct+lI5diurumUtXGO7EQvjngMZlr2qf0IxlbYjKQbc21cYcBHBZFz1FHTRHJDUasHNBPb6LcQbTFBhWS19BmtHSIgGG9V/QOtMaYmVvq84Z7QzZ/v3mBBAGC8VA1bmgGGcmbgZ9a1B4qsM+1gEaXv3TgODAFrAjyr2iakYaZ4HDmhNCiJD6drUG4zNS5SMaAAkzIrWS68Qgyzkrq7pd5htWkB3fuDAgN9B5FVyAchr3UdNmYrzpr7Kc763iWzP0xVuDP0VWLf95HGxs67Po9eDh1C/9loNacjYHoo8G0AIMQNp2dcyc6rZNzCy97FZaCf0wvAmsdoQIr/XyUz7sRm8w1+beTaGBJPaQh5nYDIwYV10RVHGe/Lgs1iZ/wElOw6ktLOthZMWHsZ3UsWTSMpRyzKhR21v7N8f+R8uAMw9i28HicEITtdjoklgNOd26Su94cx8ESp+sliZL62o+GOG+27ccmU2hhuYalPxEekXYEhSqGIlw5YKjVmABmvy47RMigrAanaTryz6beafBfKoSWFvE721Uv5UOCkJV20O40JnpNL7vv5A4ODto5w52Ytcicuq97yGBz7ZEv8FQPtRpbKbw3nTZrNb2oxfhlYW4BO8q8Yll9f0M5tJML9Eon61WlD8GBRJeoicHTpu8dsGcImumJXKH/sQy4="
    - BUILD=RELEASE

before_script:
  - mkdir BUILD && cd BUILD
  - CXX="g++ -m64" CC="gcc -m64" cmake .. -DCMAKE_BUILD_TYPE=$BUILD

script:
  - make && ctest --output-on-failure

addons:
  coverity_scan:
    project:
      name: "snps-virtualprototyping/ocx-qemu-arm"
      description: "OpenCpuX/qemu-arm - Open Source Instruction-Set Simulation Integration Kit"
    notification_email: tobies@synopsys.com
    build_command: "make"
    branch_pattern: master 
