dist: trusty
os:  linux

language: cpp

compiler:
  - gcc

env:
  global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
    - secure: "NqKIyTeur+Uz0Bjf5uXhyjyHxlfs5ST/11BGHdsh78fzY3T8E8/xf0K0rabypJP6WX8DFe3U8lFc1xoESB6SwdLh5njqFuSpCOk8PfG5ycx1uV9z9ouBTse43jwevw8yo7Uu1tef9fYA1/VvMqlLwSNEjruL285X3gljsktc4ILMBI5i7+Yvej1SUKyCYuaUxzEeYuNmn7TI5r8RBPo2SIk5XgZ8ftOHLa3dC+yldFKVsfp+zHSqd1pdBHc5iN4HBKw1lM7h+t0XX/RPeAGinioFM+TVDVn8x845eT/GFARgZmG0S0iKOhpn5T4pdafdKyXcjG7UXJz2GNiyaCrNE/O8gW46MYjIIR7rZ8zAQS7N4rakVIZIqemJVHfEBk23W8poqBcHBKU5zIoi1uoAT9Aunmu1FY6KcST/+OisHaZ0eO9ngftD70QvSwY6AIXbia4x9x1pt+A7XgbIsQsfcFNOnvS9BOa0U/PN5ac0DLwPDQSuTVxU0tSimdRLEZ0t0q3ZDdlJqK3SMyDl/VQMcuPRfrm/mmGK3zKqIzk+/Kjy4QfimtQAleK+xICh6FOOoYmdtE4BYGfk21MJNKJkXnuKI75A3H0dYl4jwmBfd7quJ/tRWauL8R2UPP4OMtv4l4Jj8pK+na7tas3amGFzsC96Hw5hPX7rgEeDOhZS+mo="
    - BUILD=RELEASE

before_script:
  - mkdir BUILD && cd BUILD
  - CXX="g++ -m64" CC="gcc -m64" cmake .. -DCMAKE_BUILD_TYPE=$BUILD

script:
  - make && ctest --output-on-failure

addons:
  coverity_scan:
    project:
      name: "snps-virtualprototyping/ocx-qemu-arm"
      description: "OpenCpuX/qemu-arm - Open Source Instruction-Set Simulation Integration Kit"
    notification_email: tobies@synopsys.com
    build_command: "make"
    branch_pattern: master
