dist: trusty
os: linux

language: cpp

compiler:
  - gcc

env:
  global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
    - secure: "a6ziQPaE6SuR+qJ7vqn1iAitiy5hu1loCN/7ITM53B6bUaxAtk7Ro0UwPy44+1Qy22HW9JNfu7qdeKPQ3PhfnXTcla0V3Wan9J8Qu2RGQRs7wU1S3cpzmxcVt4cDlf1QEP4tEtJL98uCFKmTztYl1/ZMleKA6OnIDS9yhGToGwvXp5FnMPh2s8NE+c/wU5wNnfX7KH0CgYOEv+YkmLQHM0e82XuPb5fwF/PUZAruwnQDvL5/GakLcRLC6qMm7blU4O7+IRbq3nzjxfqQECydQw55JQwgdJCu+r0//3ogRuUWOPpMqF0JDQ43jKJupigeo7naMW6tuRjLho8/CztH24mPK9yFmx1D/alecFaKCPFYAtkJx5MzthV6jfQVxhmcTC/Ww1JqATLtE7vXcAOQ2zO3aw/tbOHvNS59PMOcoOAGYIUmQqg9jKzEEebKh7+V/W3iKHEf/LDBKVoMXeUIDwX5Rczc7Gr4iYdzUG1cwfDK9VioZdqAcrgblFREXcy9r1txLbLUCp7i3WnIQO1m+FWf9chYx69aBTWQP/rWTGg1KoxNi0A4PfAK6L02r1MZcChE8+V25uB5fa4afZiFPyVbmMpkmDNbAr0ViAH/ppHk04JV/EFR8MnRSO6MEHEhmZIPX+r6SV0GvWC+ZW4KFtZHJuLaGF1az8qoAg68kBU="

    - BUILD=RELEASE

before_script:
  - mkdir BUILD && cd BUILD
  - CXX="g++ -m64" CC="gcc -m64" cmake .. -DCMAKE_BUILD_TYPE=$BUILD

script:
  - make && ctest --output-on-failure

addons:
  apt:
    packages:
      - python3.8
  coverity_scan:
    project:
      name: "snps-virtualprototyping/ocx-qemu-arm"
      description: "OpenCpuX/qemu-arm - Open Source Instruction-Set Simulation Integration Kit"
    notification_email: tobies@synopsys.com
    build_command: "make"
    branch_pattern: coverity
